# Generated by Django 5.1.6 on 2026-04-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='rol_responsable',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('JEFE_PROYECTO', 'Jefe de Proyecto / Administración'), ('ESCOLARES', 'Servicios Escolares'), ('ACADEMICO', 'División de Estudios Profesionales'), ('ALUMNO', 'Alumno')], default='ACADEMICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('JEFE_PROYECTO', 'Jefe de Proyecto / Administración'), ('ESCOLARES', 'Servicios Escolares'), ('ACADEMICO', 'División de Estudios Profesionales'), ('ALUMNO', 'Alumno')], default='ALUMNO', max_length=20, verbose_name='Rol en el sistema'),
        ),
    ]
