# Generated by Django 5.1.6 on 2026-04-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_departamento_rol_responsable_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='generacion',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 2022', null=True, verbose_name='Generación (año de ingreso)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decir')], max_length=1, verbose_name='Género'),
        ),
    ]
