# Generated by Django 5.1.6 on 2026-04-21 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_usuario_generacion_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras', to='administracion.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefes', to='administracion.departamento', verbose_name='Departamento (solo para Jefes de Proyecto)'),
        ),
    ]
