# Generated by Django 5.1.6 on 2026-04-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_carrera_departamento_usuario_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='numero_empleado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_control',
            field=models.CharField(blank=True, help_text='Número de control para alumnos o número de empleado para personal', max_length=20, null=True, verbose_name='Número de control / empleado'),
        ),
    ]
