# Generated by Django 5.1.6 on 2026-04-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_remove_usuario_numero_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellido paterno'),
        ),
    ]
