# Generated by Django 5.1.6 on 2026-04-21 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_usuario_apellido_materno_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=150, verbose_name='Apellido materno')),
                ('titulo_academico', models.CharField(help_text='Ej: Doctor en Sistemas Computacionales, Maestra en Ingeniería', max_length=250, verbose_name='Título académico')),
                ('cedula', models.CharField(help_text='Número de cédula expedida por SEP', max_length=20, verbose_name='Cédula profesional')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='administracion.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Profesor / Sinodal',
                'verbose_name_plural': 'Profesores / Sinodales',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
