# Generated by Django 5.1.6 on 2026-04-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_en_curso', models.IntegerField(default=2026, help_text='Ej: 2026', verbose_name='Año en curso')),
                ('nombre_personaje_historico', models.CharField(default='Margarita Maza', help_text='Ej: Margarita Maza', max_length=200, verbose_name='Nombre del personaje histórico')),
                ('imagen_personaje', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Foto del personaje (Pie de página izquierdo)')),
                ('logo_encabezado_gobierno', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo del Gobierno (Encabezado derecho)')),
                ('logo_institucional_extra', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo institucional extra (Pie de página derecho, ej. 100% Libre de plástico)')),
                ('direccion_institucion', models.TextField(default='Av. Instituto Tecnológico No. 418, San Andrés Ahuashuatepec, Municipio de Tzompantepec, Tlaxcala, Méx. C.P. 90491 Tel. (241) 4172010 Ext. 144, e-mail: subdplm@apizaco.tecnm.mx https://www.apizaco.tecnm.mx', verbose_name='Texto de dirección (Pie de página centro)')),
            ],
            options={
                'verbose_name': 'Configuración Institucional',
                'verbose_name_plural': 'Configuración Institucional',
            },
        ),
    ]
