# Generated by Django 5.1.6 on 2026-04-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_configuracioninstitucional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='direccion_institucion',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='imagen_personaje',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='logo_encabezado_gobierno',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='logo_institucional_extra',
        ),
        migrations.RemoveField(
            model_name='configuracioninstitucional',
            name='nombre_personaje_historico',
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='imagen_encabezado',
            field=models.ImageField(blank=True, help_text='Sube la imagen completa que servirá de membrete superior.', null=True, upload_to='configuracion/', verbose_name='Imagen completa del Encabezado'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='imagen_pie_pagina',
            field=models.ImageField(blank=True, help_text='Sube la imagen completa que servirá de pie de página.', null=True, upload_to='configuracion/', verbose_name='Imagen completa del Pie de Página'),
        ),
    ]
