# Generated by Django 5.1.6 on 2026-04-24 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_remove_configuracioninstitucional_direccion_institucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JefeDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_academico', models.CharField(help_text='Ej: Ing., M.C., Dra., Dr.', max_length=50, verbose_name='Título Académico')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=150, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=150, verbose_name='Apellido Materno')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decir')], default='F', help_text="Se usa para determinar si el cargo dice 'JEFE' o 'JEFA'", max_length=1, verbose_name='Género')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_asignado', to='administracion.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Jefe de Departamento',
                'verbose_name_plural': 'Jefes de Departamento',
            },
        ),
    ]
