# Generated by Django 5.1.6 on 2026-05-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si es True, el usuario sera forzado a cambiar su contrasena al iniciar sesion.', verbose_name='Debe cambiar contrasena'),
        ),
    ]
