# Generated by Django 5.1.6 on 2026-05-29 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_add_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='dominio_institucional',
            field=models.CharField(default='apizaco.tecnm.mx', help_text='Dominio requerido para el correo institucional (ej: apizaco.tecnm.mx)', max_length=100, verbose_name='Dominio Institucional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_institucional',
            field=models.EmailField(blank=True, help_text='Correo @apizaco.tecnm.mx o institucional para notificaciones', max_length=254, null=True, verbose_name='Correo institucional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_institucional_verificado',
            field=models.BooleanField(default=False, verbose_name='Correo institucional verificado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Correo personal verificado'),
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_a_verificar', models.EmailField(max_length=254, verbose_name='Correo a verificar')),
                ('tipo_correo', models.CharField(choices=[('INSTITUCIONAL', 'Institucional'), ('PERSONAL', 'Personal')], max_length=15)),
                ('codigo', models.CharField(max_length=6, verbose_name='Código de 6 dígitos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP de Verificación de Correo',
                'verbose_name_plural': 'OTPs de Verificación de Correos',
            },
        ),
    ]
