# Generated by Django 5.1.6 on 2026-05-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_configuracioninstitucional_dominio_institucional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', help_text='Ej: smtp.gmail.com, smtp.office365.com', max_length=255, verbose_name='Servidor SMTP (Host)'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='email_password',
            field=models.CharField(blank=True, help_text='Contraseña de aplicación generada desde el proveedor de correo', max_length=255, null=True, verbose_name='Contraseña de Aplicación'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='email_port',
            field=models.IntegerField(default=587, help_text='Ej: 587 (TLS), 465 (SSL)', verbose_name='Puerto SMTP'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='email_remitente',
            field=models.EmailField(blank=True, help_text='Cuenta de correo desde donde se enviarán las notificaciones', max_length=254, null=True, verbose_name='Correo Remitente'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Habilitar seguridad TLS (Recomendado para el puerto 587)', verbose_name='Usar TLS'),
        ),
    ]
