# Generated by Django 5.1.6 on 2026-05-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_configuracioninstitucional_email_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='rol_responsable',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('JEFE_PROYECTO', 'Jefe de Proyectos / Academia'), ('ESCOLARES', 'Servicios Escolares'), ('ACADEMICO', 'División de Estudios Profesionales'), ('ALUMNO', 'Alumno')], default='ACADEMICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('JEFE_PROYECTO', 'Jefe de Proyectos / Academia'), ('ESCOLARES', 'Servicios Escolares'), ('ACADEMICO', 'División de Estudios Profesionales'), ('ALUMNO', 'Alumno')], default='ALUMNO', max_length=20, verbose_name='Rol en el sistema'),
        ),
    ]
