# Generated by Django 5.1.6 on 2026-05-31 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_alter_departamento_rol_responsable_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_academico_nuevo', models.CharField(max_length=50, verbose_name='Título Académico')),
                ('nombre_nuevo', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('apellido_paterno_nuevo', models.CharField(max_length=150, verbose_name='Apellido Paterno')),
                ('apellido_materno_nuevo', models.CharField(blank=True, max_length=150, verbose_name='Apellido Materno')),
                ('genero_nuevo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decir')], default='F', max_length=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_jefe', to='administracion.departamento')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cambio_jefe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Jefe',
                'verbose_name_plural': 'Solicitudes de Cambio de Jefe',
            },
        ),
    ]
