# Generated by Django 5.1.6 on 2026-05-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_solicitudcambiojefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='departamento',
        ),
        migrations.AddField(
            model_name='profesor',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='administracion.departamento', verbose_name='Departamentos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Correo alternativo verificado'),
        ),
    ]
