# Generated by Django 5.1.6 on 2026-05-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_remove_profesor_departamento_profesor_departamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='rol_responsable',
        ),
    ]
