# Generated by Django 5.1.6 on 2026-06-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_remove_departamento_rol_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='ultima_actualizacion',
            field=models.FloatField(default=0.0, help_text='Timestamp Unix de la última vez que se modificó un registro importante.', verbose_name='Última actualización global'),
        ),
    ]
