# Generated by Django 5.1.6 on 2026-06-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_configuracioninstitucional_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='permitir_jefe_proyectos_cambiar_jefe_departamento',
            field=models.BooleanField(default=False, help_text='Si está activo, los Jefes de Proyecto no necesitarán solicitar el cambio a un administrador, el cambio será directo.', verbose_name='Permitir a Jefes de Proyecto cambiar Jefe de Departamento directamente'),
        ),
        migrations.AlterField(
            model_name='configuracioninstitucional',
            name='ultima_actualizacion',
            field=models.FloatField(default=0.0, help_text='Timestamp interno para forzar la actualización en tiempo real de los clientes.', verbose_name='Última actualización global'),
        ),
    ]
