# Generated by Django 5.1.6 on 2026-06-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0021_configuracioninstitucional_permitir_jefe_proyectos_cambiar_jefe_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='color_botones',
            field=models.CharField(default='#0057B8', help_text='Color en formato hexadecimal.', max_length=7, verbose_name='Color Secundario (Hovers y enlaces)'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='color_cintillo',
            field=models.CharField(default='#611232', help_text='Color en formato hexadecimal.', max_length=7, verbose_name='Color de Fondo del Cintillo'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='color_header',
            field=models.CharField(default='#1B396A', help_text='Color en formato hexadecimal.', max_length=7, verbose_name='Color de Barra de Navegación'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='color_menu',
            field=models.CharField(default='#003B73', help_text='Color en formato hexadecimal.', max_length=7, verbose_name='Color Primario (Botones y acentos)'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='imagen_cintillo',
            field=models.ImageField(blank=True, help_text='Opcional. Sube una imagen para reemplazar los logos del cintillo superior.', null=True, upload_to='configuracion/', verbose_name='Imagen del Cintillo'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='logo_sistema',
            field=models.ImageField(blank=True, help_text='Logotipo para la barra de navegación (se recomienda PNG transparente).', null=True, upload_to='configuracion/', verbose_name='Logotipo del Sistema'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='mostrar_cintillo',
            field=models.BooleanField(default=True, help_text='Activar para mostrar la barra superior con los logos institucionales/gubernamentales.', verbose_name='Mostrar Cintillo Gubernamental'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='nombre_institucion',
            field=models.CharField(default='Instituto Tecnológico de Apizaco', max_length=255, verbose_name='Nombre de la Institución'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='siglas',
            field=models.CharField(default='ITApizaco', max_length=50, verbose_name='Siglas de la Institución'),
        ),
    ]
