# Generated by Django 5.1.6 on 2026-06-17 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_configuracioninstitucional_color_botones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jefedepartamento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Solo debe haber un jefe activo por departamento a la vez.', verbose_name='¿Es el jefe activo actualmente?'),
        ),
        migrations.AlterField(
            model_name='jefedepartamento',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefes_historial', to='administracion.departamento', verbose_name='Departamento'),
        ),
    ]
