# Generated by Django 5.1.6 on 2026-09-01 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_jefedepartamento_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='clave_ctt',
            field=models.CharField(blank=True, help_text='Ej: 29DIT0037U', max_length=20, verbose_name='Clave CTT institucional'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='director_cargo',
            field=models.CharField(blank=True, default='Director(a)', max_length=200, verbose_name='Cargo del Director(a)'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='director_genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decir')], max_length=1, verbose_name='Género del Director(a)'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='director_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del Director(a)'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='jefe_escolares_cargo',
            field=models.CharField(blank=True, default='Jefe del Departamento de Servicios Escolares', max_length=200, verbose_name='Cargo Jefe Escolares'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='jefe_escolares_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Jefe del Depto. de Servicios Escolares'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='sistema_configurado',
            field=models.BooleanField(default=False, help_text='Indica que la configuración inicial obligatoria fue completada.', verbose_name='Sistema configurado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('OFICINA_TITULACION', 'Oficina de Titulación'), ('FINANZAS', 'Finanzas'), ('CENTRO_COMPUTO', 'Centro de Cómputo'), ('CENTRO_INFORMACION', 'Centro de Información'), ('JEFE_ACADEMIA', 'Jefe de Academia'), ('ALUMNO', 'Alumno'), ('JEFE_PROYECTO', 'Jefe de Proyectos (legado)'), ('ESCOLARES', 'Servicios Escolares (legado)'), ('ACADEMICO', 'División Académica (legado)')], default='ALUMNO', max_length=20, verbose_name='Rol en el sistema'),
        ),
        migrations.CreateModel(
            name='PeriodoActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('motivo', models.CharField(blank=True, help_text='Ej: vacaciones, incapacidad, baja temporal', max_length=200, verbose_name='Motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Periodo vigente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_actividad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Periodo de actividad',
                'verbose_name_plural': 'Periodos de actividad',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
