# Generated by Django 5.1.6 on 2026-09-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0026_fix_admin_email_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='logo_sep',
            field=models.ImageField(blank=True, help_text='Logo de la Secretaría de Educación Pública (encabezado institucional).', null=True, upload_to='configuracion/logos/', verbose_name='Logo SEP'),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='logo_tecnm',
            field=models.ImageField(blank=True, help_text='Logo del Tecnológico Nacional de México (encabezado institucional).', null=True, upload_to='configuracion/logos/', verbose_name='Logo TecNM'),
        ),
        migrations.AlterField(
            model_name='configuracioninstitucional',
            name='logo_sistema',
            field=models.ImageField(blank=True, help_text='Logotipo del instituto/plantel (encabezado y barra de navegación). Se recomienda PNG transparente.', null=True, upload_to='configuracion/logos/', verbose_name='Logo del plantel'),
        ),
    ]
