# Generated by Django 5.1.6 on 2026-09-17 21:59

from django.db import migrations, models


def migrar_generacion_a_periodos(apps, schema_editor):
    Usuario = apps.get_model('administracion', 'Usuario')
    for u in Usuario.objects.exclude(generacion__isnull=True).iterator():
        if u.generacion:
            u.periodo_inicio_ciclo = 'AGO_DIC'
            u.periodo_inicio_anio = u.generacion
            u.save(update_fields=['periodo_inicio_ciclo', 'periodo_inicio_anio'])


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0028_contacto_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='periodo_egreso_anio',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 2026', null=True, verbose_name='Periodo de egreso (año)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo_egreso_ciclo',
            field=models.CharField(blank=True, choices=[('ENE_JUN', 'Enero – Junio'), ('AGO_DIC', 'Agosto – Diciembre')], help_text='Ej: Enero – Junio', max_length=10, verbose_name='Periodo de egreso (ciclo)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo_inicio_anio',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 2021', null=True, verbose_name='Periodo de inicio (año)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo_inicio_ciclo',
            field=models.CharField(blank=True, choices=[('ENE_JUN', 'Enero – Junio'), ('AGO_DIC', 'Agosto – Diciembre')], help_text='Ej: Agosto – Diciembre', max_length=10, verbose_name='Periodo de inicio (ciclo)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestres_cursados',
            field=models.PositiveIntegerField(blank=True, help_text='Calculado a partir de los periodos de inicio y egreso.', null=True, verbose_name='Semestres cursados'),
        ),
        migrations.RunPython(migrar_generacion_a_periodos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='usuario',
            name='generacion',
        ),
    ]
