# Generated by Django 5.1.6 on 2026-03-31 23:34

import django.db.models.deletion
import expediente.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la modalidad')),
                ('clave', models.CharField(max_length=30, verbose_name='Clave (ej: RESIDENCIA, TESIS)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modalidad de Titulación',
                'verbose_name_plural': 'Modalidades de Titulación',
                'ordering': ['plan_estudios', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Plan de Estudios')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan de Estudios',
                'verbose_name_plural': 'Planes de Estudios',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION_ACADEMICO', 'En Revisión — División de Estudios'), ('RECHAZADO_ACADEMICO', 'Rechazado por División de Estudios'), ('EN_CORRECCION', 'En Corrección por el Alumno'), ('DOCUMENTOS_PENDIENTES', 'Carga de Documentos Pendiente'), ('EN_REVISION_DOCUMENTOS', 'Documentos en Revisión'), ('LISTO_INTEGRACION', 'Listo para Integración (Escolares)'), ('INTEGRADO', 'Expediente Integrado'), ('ENVIADO_CDMX', 'Enviado a Revisión CDMX'), ('RECHAZADO_CDMX', 'Rechazado por CDMX'), ('APROBADO_CDMX', 'Aprobado por CDMX'), ('EMPASTADO_PENDIENTE', 'Pendiente de Recepción de Empastado'), ('EMPASTADO_RECIBIDO', 'Empastado Recibido'), ('JURADO_ASIGNADO', 'Jurado Asignado'), ('ACTO_PROGRAMADO', 'Acto Protocolario Programado'), ('CONCLUIDO', 'Proceso Concluido'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=40, verbose_name='Estado del proceso')),
                ('titulo_trabajo', models.CharField(blank=True, max_length=500, verbose_name='Título del trabajo / proyecto')),
                ('nombre_empresa', models.CharField(blank=True, max_length=300, verbose_name='Empresa / Organización (para residencia)')),
                ('fotografia_digital', models.ImageField(blank=True, null=True, upload_to='fotografias/%Y/', verbose_name='Fotografía óvalo (digital)')),
                ('fotografia_fisica_entregada', models.BooleanField(default=False, verbose_name='¿Fotografía física entregada?')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_conclusion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conclusión')),
                ('observaciones_division', models.TextField(blank=True, verbose_name='Observaciones de División de Estudios')),
                ('alumno', models.OneToOneField(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.PROTECT, related_name='expediente', to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expediente.modalidad', verbose_name='Modalidad de Titulación')),
            ],
            options={
                'verbose_name': 'Expediente de Titulación',
                'verbose_name_plural': 'Expedientes de Titulación',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='EnvioCDMX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oficio', models.CharField(blank=True, max_length=100, verbose_name='Número de oficio de envío')),
                ('fecha_envio', models.DateField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('estado', models.CharField(choices=[('PREPARADO', 'Preparado para envío'), ('ENVIADO', 'Enviado a CDMX/TecNM'), ('EN_REVISION', 'En revisión en CDMX'), ('APROBADO', 'Aprobado por CDMX'), ('RECHAZADO', 'Rechazado por CDMX')], default='PREPARADO', max_length=15, verbose_name='Estado')),
                ('observaciones_envio', models.TextField(blank=True, verbose_name='Observaciones del envío')),
                ('fecha_respuesta', models.DateField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('observaciones_cdmx', models.TextField(blank=True, verbose_name='Observaciones de CDMX (en caso de rechazo)')),
                ('numero_registro_titulo', models.CharField(blank=True, max_length=100, verbose_name='Número de registro del título (si fue aprobado)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_cdmx_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cdmx', to='expediente.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Envío a CDMX',
                'verbose_name_plural': 'Envíos a CDMX',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=expediente.models.upload_documento_path, verbose_name='Archivo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de carga'), ('CARGADO', 'Cargado — Sin Revisar'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REQUIERE_CORRECCION', 'Requiere Corrección')], default='PENDIENTE', max_length=25, verbose_name='Estado')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('fecha_carga', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de carga')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas_alumno', models.TextField(blank=True, verbose_name='Notas del alumno')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expediente.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['tipo_documento__orden'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionJurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carta', models.DateField(verbose_name='Fecha de carta de asignación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurados_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurado_presidente', to=settings.AUTH_USER_MODEL, verbose_name='Presidente del jurado')),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurado_secretario', to=settings.AUTH_USER_MODEL, verbose_name='Secretario del jurado')),
                ('vocal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurado_vocal', to=settings.AUTH_USER_MODEL, verbose_name='Vocal del jurado')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jurado', to='expediente.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Asignación de Jurado',
                'verbose_name_plural': 'Asignaciones de Jurado',
            },
        ),
        migrations.CreateModel(
            name='ActoProtocolario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acto', models.DateTimeField(verbose_name='Fecha y hora del acto')),
                ('lugar', models.CharField(max_length=300, verbose_name='Lugar / Sala')),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('APROBADO_MENCION', 'Aprobado con Mención Honorífica'), ('SUSPENDIDO', 'Suspendido'), ('NO_PRESENTADO', 'No se presentó')], default='PENDIENTE', max_length=20, verbose_name='Resultado')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Calificación (si aplica)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('programado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actos_programados', to=settings.AUTH_USER_MODEL, verbose_name='Programado por')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expediente.asignacionjurado', verbose_name='Jurado asignado')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acto_protocolario', to='expediente.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Acto Protocolario',
                'verbose_name_plural': 'Actos Protocolarios',
                'ordering': ['fecha_acto'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción realizada')),
                ('departamento', models.CharField(blank=True, max_length=15, verbose_name='Departamento')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='expediente.documento', verbose_name='Documento')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Historial de Documento',
                'verbose_name_plural': 'Historial de Documentos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=40, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=40, verbose_name='Estado nuevo')),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='expediente.expediente', verbose_name='Expediente')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Historial del Expediente',
                'verbose_name_plural': 'Historial de Expedientes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='modalidad',
            name='plan_estudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='expediente.planestudios', verbose_name='Plan de Estudios'),
        ),
        migrations.CreateModel(
            name='RecepcionEmpastado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de recepción')),
                ('estado', models.CharField(choices=[('REVISADO', 'Revisado y Aceptado'), ('OBSERVACIONES', 'Con Observaciones'), ('RECHAZADO', 'Rechazado')], default='REVISADO', max_length=20, verbose_name='Estado de revisión física')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empastado', to='expediente.expediente', verbose_name='Expediente')),
                ('recibido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empastados_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Recepción de Empastado',
                'verbose_name_plural': 'Recepciones de Empastado',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('descripcion_ayuda', models.TextField(help_text='Describe cómo debe ser el documento (formato, requisitos, etc.)', verbose_name='Instrucciones para el alumno')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='¿Es obligatorio?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de presentación')),
                ('valida_division', models.BooleanField(default=True, verbose_name='Valida División de Estudios')),
                ('valida_escolares', models.BooleanField(default=True, verbose_name='Valida Servicios Escolares')),
                ('acepta_solo_pdf', models.BooleanField(default=True, verbose_name='Solo acepta PDF')),
                ('es_fotografia', models.BooleanField(default=False, verbose_name='¿Es fotografía?')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='expediente.modalidad', verbose_name='Modalidad')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Requerido',
                'verbose_name_plural': 'Tipos de Documentos Requeridos',
                'ordering': ['modalidad', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expediente.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.CreateModel(
            name='ValidacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('DIVISION', 'División de Estudios Profesionales'), ('ESCOLARES', 'Servicios Escolares')], max_length=15, verbose_name='Departamento validador')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REQUIERE_CORRECCION', 'Requiere Corrección')], default='PENDIENTE', max_length=25, verbose_name='Estado de validación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Motivo de rechazo')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de última acción')),
                ('fecha_primera_revision', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='expediente.documento', verbose_name='Documento')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Validación de Documento',
                'verbose_name_plural': 'Validaciones de Documentos',
                'unique_together': {('documento', 'departamento')},
            },
        ),
    ]
