# Generated by Django 5.1.6 on 2026-04-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='fotografia_fisica_entregada',
        ),
        migrations.AddField(
            model_name='expediente',
            name='foto_fisica_division',
            field=models.BooleanField(default=False, verbose_name='¿Foto física entregada en División?'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='foto_fisica_escolares',
            field=models.BooleanField(default=False, verbose_name='¿Foto física entregada en Escolares?'),
        ),
    ]
