# Generated by Django 5.1.6 on 2026-04-21 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_profesor'),
        ('expediente', '0002_remove_expediente_fotografia_fisica_entregada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionjurado',
            name='fecha_carta',
        ),
        migrations.RemoveField(
            model_name='asignacionjurado',
            name='vocal',
        ),
        migrations.AddField(
            model_name='asignacionjurado',
            name='fecha_acto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora del acto protocolario'),
        ),
        migrations.AddField(
            model_name='asignacionjurado',
            name='fecha_oficio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del oficio'),
        ),
        migrations.AddField(
            model_name='asignacionjurado',
            name='lugar_acto',
            field=models.CharField(blank=True, help_text='Ej: SALA MAGNA (edificio T)', max_length=300, verbose_name='Lugar del acto'),
        ),
        migrations.AddField(
            model_name='asignacionjurado',
            name='numero_oficio',
            field=models.CharField(blank=True, help_text='Ej: S.C./OPV/0099/2026', max_length=50, verbose_name='Número de oficio'),
        ),
        migrations.AddField(
            model_name='asignacionjurado',
            name='vocal_propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurado_vocal_prop', to='administracion.profesor', verbose_name='Vocal Propietario/a'),
        ),
        migrations.AddField(
            model_name='asignacionjurado',
            name='vocal_suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurado_vocal_sup', to='administracion.profesor', verbose_name='Vocal Suplente'),
        ),
        migrations.AlterField(
            model_name='asignacionjurado',
            name='presidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurado_presidente', to='administracion.profesor', verbose_name='Presidente del jurado'),
        ),
        migrations.AlterField(
            model_name='asignacionjurado',
            name='secretario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurado_secretario', to='administracion.profesor', verbose_name='Secretario/a del jurado'),
        ),
    ]
