# Generated by Django 5.1.6 on 2026-04-29 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_remove_asignacionjurado_fecha_carta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionActo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('SECRETARIO', 'Secretario/a'), ('VOCAL_PROPIETARIO', 'Vocal Propietario/a'), ('VOCAL_SUPLENTE', 'Vocal Suplente'), ('ALUMNO', 'Alumno/a')], max_length=20, verbose_name='Rol en el jurado')),
                ('nombre_participante', models.CharField(max_length=300, verbose_name='Nombre del participante')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de confirmación')),
                ('confirmado', models.BooleanField(default=False, verbose_name='¿Confirmado?')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('acto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='expediente.actoprotocolario', verbose_name='Acto Protocolario')),
            ],
            options={
                'verbose_name': 'Confirmación de Asistencia',
                'verbose_name_plural': 'Confirmaciones de Asistencia',
                'unique_together': {('acto', 'rol')},
            },
        ),
    ]
