# Generated by Django 5.2.12 on 2026-05-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0004_confirmacion_acto'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_pago/%Y/', verbose_name='Comprobante de Pago (PDF)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_subida_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_validacion_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='pago_observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones de Validación del Pago'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='pago_validado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Carga'), ('CARGADO', 'Comprobante Cargado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado de Validación del Pago'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION_ACADEMICO', 'En Revisión — División de Estudios'), ('RECHAZADO_ACADEMICO', 'Rechazado por División de Estudios'), ('EN_CORRECCION', 'En Corrección por el Alumno'), ('DOCUMENTOS_PENDIENTES', 'Carga de Documentos Pendiente'), ('EN_REVISION_DOCUMENTOS', 'Documentos en Revisión'), ('LISTO_INTEGRACION', 'Listo para Integración (Escolares)'), ('PAGO_PENDIENTE', 'Pago de Titulación Pendiente'), ('PAGO_EN_REVISION', 'Pago en Revisión'), ('INTEGRADO', 'Expediente Integrado'), ('ENVIADO_CDMX', 'Enviado a Revisión CDMX'), ('RECHAZADO_CDMX', 'Rechazado por CDMX'), ('APROBADO_CDMX', 'Aprobado por CDMX'), ('EMPASTADO_PENDIENTE', 'Pendiente de Recepción de Empastado'), ('EMPASTADO_RECIBIDO', 'Empastado Recibido'), ('JURADO_ASIGNADO', 'Jurado Asignado'), ('ACTO_PROGRAMADO', 'Acto Protocolario Programado'), ('CONCLUIDO', 'Proceso Concluido'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=40, verbose_name='Estado del proceso'),
        ),
    ]
