# Generated by Django 5.2.12 on 2026-05-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_pagos_titulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_ultimo_recordatorio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del último recordatorio'),
        ),
    ]
