# Generated by Django 5.2.12 on 2026-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0006_expediente_fecha_ultimo_recordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='constancia_no_inconveniencia',
            field=models.FileField(blank=True, null=True, upload_to='constancias/%Y/', verbose_name='Constancia de No Inconveniencia (PDF firmado)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_constancia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de carga de la constancia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION_ACADEMICO', 'En Revisión — División de Estudios'), ('RECHAZADO_ACADEMICO', 'Rechazado por División de Estudios'), ('EN_CORRECCION', 'En Corrección por el Alumno'), ('DOCUMENTOS_PENDIENTES', 'Carga de Documentos Pendiente'), ('EN_REVISION_DOCUMENTOS', 'Documentos en Revisión'), ('LISTO_INTEGRACION', 'Listo para Integración (Escolares)'), ('PAGO_PENDIENTE', 'Pago de Titulación Pendiente'), ('PAGO_EN_REVISION', 'Pago en Revisión'), ('INTEGRADO', 'Expediente Integrado'), ('EMPASTADO_PENDIENTE', 'Pendiente de Recepción de Empastado'), ('EMPASTADO_RECIBIDO', 'Empastado Recibido'), ('JURADO_ASIGNADO', 'Jurado Asignado'), ('ACTO_PROGRAMADO', 'Acto Protocolario Programado'), ('ACTA_EXENCION', 'Acta de Exención de Examen Profesional'), ('ENVIADO_CDMX', 'Enviado a Revisión CDMX'), ('RECHAZADO_CDMX', 'Rechazado por CDMX'), ('APROBADO_CDMX', 'Aprobado por CDMX'), ('CONCLUIDO', 'Proceso Concluido'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=40, verbose_name='Estado del proceso'),
        ),
    ]
