# Generated by Django 5.2.12 on 2026-05-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0007_expediente_constancia_no_inconveniencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='cedula_profesional_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cedulas/%Y/', verbose_name='Cédula Profesional (PDF)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_cita_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Cita para Entrega'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_subida_cedula',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='instrucciones_cita',
            field=models.TextField(blank=True, verbose_name='Instrucciones para la Cita'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='observaciones_cedula',
            field=models.TextField(blank=True, verbose_name='Observaciones de revisión de cédula'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION_ACADEMICO', 'En Revisión — División de Estudios'), ('RECHAZADO_ACADEMICO', 'Rechazado por División de Estudios'), ('EN_CORRECCION', 'En Corrección por el Alumno'), ('DOCUMENTOS_PENDIENTES', 'Carga de Documentos Pendiente'), ('EN_REVISION_DOCUMENTOS', 'Documentos en Revisión'), ('LISTO_INTEGRACION', 'Listo para Integración (Escolares)'), ('PAGO_PENDIENTE', 'Pago de Titulación Pendiente'), ('PAGO_EN_REVISION', 'Pago en Revisión'), ('INTEGRADO', 'Expediente Integrado'), ('EMPASTADO_PENDIENTE', 'Pendiente de Recepción de Empastado'), ('EMPASTADO_RECIBIDO', 'Empastado Recibido'), ('JURADO_ASIGNADO', 'Jurado Asignado'), ('ACTO_PROGRAMADO', 'Acto Protocolario Programado'), ('ACTA_EXENCION', 'Acta de Exención de Examen Profesional'), ('TRAMITE_DGP', 'Trámite DGP (Validación y Registro)'), ('CEDULA_EN_REVISION', 'Revisión de Cédula Profesional'), ('CEDULA_RECHAZADA', 'Cédula Profesional Rechazada'), ('CITA_ENTREGA', 'Cita de Entrega Programada'), ('CONCLUIDO', 'Proceso Concluido'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=40, verbose_name='Estado del proceso'),
        ),
        migrations.DeleteModel(
            name='EnvioCDMX',
        ),
    ]
