# Generated by Django 5.2.12 on 2026-05-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0009_alter_expediente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='acta_exencion_pdf',
            field=models.FileField(blank=True, null=True, upload_to='actas_exencion/%Y/', verbose_name='Acta de Exención de Examen Profesional (PDF)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_subida_acta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subida del acta'),
        ),
    ]
