# Generated by Django 5.2.12 on 2026-05-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0010_acta_exencion_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='fecha_subida_acta',
        ),
        migrations.AddField(
            model_name='expediente',
            name='notificacion_dgp_enviada',
            field=models.BooleanField(default=False, verbose_name='Notificación DGP enviada'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='acta_exencion_pdf',
            field=models.FileField(blank=True, null=True, upload_to='actas_exencion/', verbose_name='Acta de Exención / Examen (PDF)'),
        ),
    ]
