# Generated by Django 5.2.12 on 2026-05-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0011_remove_expediente_fecha_subida_acta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='datos_dgp_confirmados',
            field=models.BooleanField(default=False, verbose_name='Datos DGP confirmados por el alumno'),
        ),
    ]
