# Generated by Django 5.1.6 on 2026-05-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0012_expediente_datos_dgp_confirmados'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionjurado',
            name='oficio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='oficios_jurado/', verbose_name='PDF del Oficio de Jurado'),
        ),
    ]
