# Generated by Django 5.2.12 on 2026-05-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0012_expediente_datos_dgp_confirmados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION_ACADEMICO', 'En Revisión — División de Estudios'), ('RECHAZADO_ACADEMICO', 'Rechazado por División de Estudios'), ('EN_CORRECCION', 'En Corrección por el Alumno'), ('DOCUMENTOS_PENDIENTES', 'Carga de Documentos Pendiente'), ('EN_REVISION_DOCUMENTOS', 'Documentos en Revisión'), ('LISTO_INTEGRACION', 'Listo para Integración (Escolares)'), ('RECIBI_PAPEL_ORIGINAL', 'Papeles originales integrados'), ('PAGO_PENDIENTE', 'Pago de Titulación Pendiente'), ('PAGO_EN_REVISION', 'Pago en Revisión'), ('ESPERANDO_CONSTANCIA', 'Esperando Constancia de No Inconveniencia'), ('CONSTANCIA_EN_REVISION', 'Constancia en Revisión Académica'), ('INTEGRADO', 'Expediente Integrado'), ('EMPASTADO_PENDIENTE', 'Pendiente de Recepción de Empastado'), ('EMPASTADO_RECIBIDO', 'Empastado Recibido'), ('JURADO_ASIGNADO', 'Jurado Asignado'), ('ACTO_PROGRAMADO', 'Acto Protocolario Programado'), ('ACTA_EXENCION', 'Acta de Exención de Examen Profesional'), ('TRAMITE_DGP', 'Captura en plataforma (e-títulos) de TNM'), ('CEDULA_EN_REVISION', 'Revisión de Cédula Profesional'), ('CEDULA_RECHAZADA', 'Cédula Profesional Rechazada'), ('CITA_ENTREGA', 'Cita de Entrega Programada'), ('CONCLUIDO', 'Proceso Concluido'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=40, verbose_name='Estado del proceso'),
        ),
    ]
