# Generated by Django 5.1.6 on 2026-05-31 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_solicitudcambiojefe'),
        ('expediente', '0013_asignacionjurado_oficio_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionjurado',
            name='notas',
        ),
        migrations.AddField(
            model_name='asignacionjurado',
            name='solicitud_jefe_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_jurado', to='administracion.solicitudcambiojefe', verbose_name='Solicitud de Jefe Usada'),
        ),
        migrations.AlterField(
            model_name='asignacionjurado',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurados_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionjurado',
            name='oficio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='oficios_jurado/', verbose_name='Oficio de Asignación en PDF'),
        ),
    ]
