# Generated by Django 5.2.12 on 2026-05-31 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0013_alter_expediente_estado'),
        ('expediente', '0014_remove_asignacionjurado_notas_and_more'),
    ]

    operations = [
    ]
