# Generated by Django 5.1.6 on 2026-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0015_merge_20260531_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='foto_fisica_division',
            field=models.BooleanField(default=False, verbose_name='¿Foto física entregada en División de Estudios Profesionales?'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='foto_fisica_escolares',
            field=models.BooleanField(default=False, verbose_name='¿Foto física entregada en Servicios Escolares?'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='observaciones_division',
            field=models.TextField(blank=True, verbose_name='Observaciones de División de Estudios Profesionales'),
        ),
    ]
