# Generated by Django 5.1.6 on 2026-06-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0016_alter_expediente_foto_fisica_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='preficha_enviada',
            field=models.BooleanField(default=False, verbose_name='¿Preficha de Pago enviada?'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='preficha_pago',
            field=models.FileField(blank=True, null=True, upload_to='prefichas/%Y/', verbose_name='Preficha de Pago (PDF)'),
        ),
    ]
