# Generated by Django 5.1.6 on 2026-06-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0016_alter_expediente_foto_fisica_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actoprotocolario',
            name='resultado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('SUSPENDIDO', 'Suspendido'), ('NO_PRESENTADO', 'No se presentó')], default='PENDIENTE', max_length=20, verbose_name='Resultado'),
        ),
    ]
