# Generated by Django 5.1.6 on 2026-09-01 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_siget_fase0'),
        ('expediente', '0017_alter_actoprotocolario_resultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validaciondocumento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='actoprotocolario',
            name='hora_escalonada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora escalonada (EGEL)'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='observaciones_revision',
            field=models.TextField(blank=True, verbose_name='Observaciones de revisión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_asesorados', to='administracion.profesor', verbose_name='Asesor'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='certificacion_final_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificaciones/%Y/', verbose_name='Certificación de exención'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='certificado_digital',
            field=models.FileField(blank=True, null=True, upload_to='certificados/%Y/', verbose_name='Certificado digitalizado'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='constancia_no_adeudos',
            field=models.FileField(blank=True, null=True, upload_to='constancias_adeudos/%Y/', verbose_name='Constancia de no adeudos'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='oficio_publicacion_escaneado',
            field=models.FileField(blank=True, null=True, upload_to='oficios_publicacion_escaneados/%Y/', verbose_name='Oficio de publicación escaneado (firmado)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='oficio_publicacion_pdf',
            field=models.FileField(blank=True, null=True, upload_to='oficios_publicacion/%Y/', verbose_name='Oficio de autorización de publicación'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='plan_estudios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='expediente.planestudios', verbose_name='Plan de estudios'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='formatos_admitidos',
            field=models.JSONField(default=list, help_text='Lista de formatos: pdf, jpg, png, webp', verbose_name='Formatos admitidos'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='tamano_max_mb',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='Tamaño máximo (MB)'),
        ),
        migrations.AlterField(
            model_name='asignacionjurado',
            name='oficio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='oficios_jurado/', verbose_name='PDF del Oficio de Jurado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('DATOS_EXPEDIENTE', 'Datos del expediente'), ('CERTIFICADO_PENDIENTE_CITA', 'Certificado — pendiente de cita'), ('CERTIFICADO_CITA_PROGRAMADA', 'Certificado — cita programada'), ('CERTIFICADO_FIRMADO', 'Certificado firmado'), ('CARGA_DOCUMENTOS', 'Carga de documentos'), ('EN_REVISION', 'En revisión — Oficina de Titulación'), ('EN_CORRECCION', 'En corrección por el alumno'), ('EXPEDIENTE_APROBADO', 'Expediente aprobado'), ('OFICIO_GENERADO', 'Oficio de publicación generado'), ('OFICIO_CITA_PROGRAMADA', 'Oficio — cita programada'), ('OFICIO_FIRMADO', 'Oficio firmado y cargado'), ('PAGO_PENDIENTE', 'Pago pendiente'), ('PAGO_VALIDADO', 'Pago validado'), ('ADEUDOS_EN_REVISION', 'Confirmación de no adeudos'), ('DOCUMENTOS_OFICIALES_LISTOS', 'Documentos oficiales listos'), ('JURADO_ASIGNADO', 'Jurado asignado'), ('PROTOCOLO_PROGRAMADO', 'Protocolo programado'), ('ACTO_REALIZADO', 'Acto protocolario realizado'), ('CONCLUIDO', 'Proceso concluido'), ('CANCELADO', 'Cancelado'), ('BORRADOR', 'Borrador (legado)'), ('EN_REVISION_ACADEMICO', 'Revisión académica (legado)'), ('RECHAZADO_ACADEMICO', 'Rechazado académico (legado)'), ('DOCUMENTOS_PENDIENTES', 'Documentos pendientes (legado)'), ('EN_REVISION_DOCUMENTOS', 'Revisión documentos (legado)'), ('LISTO_INTEGRACION', 'Listo integración (legado)'), ('PAGO_EN_REVISION', 'Pago en revisión (legado)'), ('INTEGRADO', 'Integrado (legado)'), ('EMPASTADO_PENDIENTE', 'Empastado pendiente (legado)'), ('EMPASTADO_RECIBIDO', 'Empastado recibido (legado)'), ('ACTO_PROGRAMADO', 'Acto programado (legado)'), ('ACTA_EXENCION', 'Acta exención (legado)')], default='DATOS_EXPEDIENTE', max_length=40, verbose_name='Estado del proceso'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='acepta_solo_pdf',
            field=models.BooleanField(default=True, verbose_name='Solo PDF (legado)'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='es_fotografia',
            field=models.BooleanField(default=False, verbose_name='Es fotografía (legado)'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='valida_division',
            field=models.BooleanField(default=True, verbose_name='Valida División (legado)'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='valida_escolares',
            field=models.BooleanField(default=True, verbose_name='Valida Escolares (legado)'),
        ),
        migrations.AlterField(
            model_name='validaciondocumento',
            name='departamento',
            field=models.CharField(default='OFICINA', max_length=15, verbose_name='Departamento validador (legado)'),
        ),
        migrations.AlterField(
            model_name='validaciondocumento',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacion', to='expediente.documento', verbose_name='Documento'),
        ),
        migrations.CreateModel(
            name='GrupoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del grupo')),
                ('criterio', models.CharField(blank=True, max_length=300, verbose_name='Criterio')),
                ('fecha', models.DateField(verbose_name='Fecha del acto')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('lugar', models.CharField(max_length=300, verbose_name='Lugar')),
                ('es_egel', models.BooleanField(default=False, verbose_name='¿Es EGEL? (horarios escalonados)')),
                ('intervalo_minutos', models.PositiveIntegerField(default=30, verbose_name='Intervalo entre alumnos (min)')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_protocolo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de protocolo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='actoprotocolario',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actos', to='expediente.grupoprotocolo', verbose_name='Grupo de protocolo'),
        ),
        migrations.CreateModel(
            name='LoteCitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=200, verbose_name='Criterio del lote')),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('OFICIO_PUBLICACION', 'Oficio publicación')], default='CERTIFICADO', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_citacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de citación',
                'verbose_name_plural': 'Lotes de citación',
            },
        ),
        migrations.CreateModel(
            name='CitaDocumentoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('OFICIO_PUBLICACION', 'Oficio de publicación')], max_length=30)),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('lugar', models.CharField(max_length=300, verbose_name='Lugar')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA_ALUMNO', 'Confirmada por alumno'), ('REPROGRAMACION_SOLICITADA', 'Reprogramación solicitada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('propuesta_alumno_fecha', models.DateTimeField(blank=True, null=True)),
                ('propuesta_alumno_notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_fisicas', to='expediente.expediente', verbose_name='Expediente')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='expediente.lotecitacion')),
            ],
            options={
                'verbose_name': 'Cita documento físico',
                'verbose_name_plural': 'Citas documentos físicos',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigencia', models.DateField(blank=True, null=True)),
                ('pdf_referencia', models.FileField(blank=True, null=True, upload_to='referencias_pago/%Y/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_pago', to='expediente.expediente')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referencia de pago',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionAdeudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('FINANZAS', 'Finanzas'), ('CENTRO_COMPUTO', 'Centro de Cómputo'), ('CENTRO_INFORMACION', 'Centro de Información')], max_length=20)),
                ('sin_adeudos', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('confirmado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adeudos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones_adeudo', to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Confirmación de adeudo',
                'unique_together': {('expediente', 'area')},
            },
        ),
    ]
