# Generated by Django 5.1.6 on 2026-06-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0017_alter_actoprotocolario_resultado'),
        ('expediente', '0017_expediente_preficha_enviada_expediente_preficha_pago'),
    ]

    operations = [
    ]
