# Generated by Django 5.2.12 on 2026-09-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0018_merge_20260623_2231'),
        ('expediente', '0022_oficio_firmado_a_pago_pendiente'),
    ]

    operations = [
    ]
