# Generated by Django 5.2.12 on 2026-09-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0023_merge_20260905_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='preficha_enviada',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='preficha_pago',
        ),
    ]
