# Generated by Django 5.2.12 on 2026-09-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0024_remove_expediente_preficha_enviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionjurado',
            name='documentos_protocolo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos_protocolo/', verbose_name='Documentos de Protocolo (PDF)'),
        ),
        migrations.AlterField(
            model_name='asignacionjurado',
            name='oficio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='oficios_jurado/', verbose_name='Oficio de Asignación (PDF)'),
        ),
    ]
