# Generated by Django 5.2.12 on 2026-09-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0025_asignacionjurado_documentos_protocolo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='certificacion_final_escaneada',
            field=models.FileField(blank=True, null=True, upload_to='certificaciones_firmadas/%Y/', verbose_name='Certificación de exención (Firmada)'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='certificacion_final_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificaciones/%Y/', verbose_name='Certificación de exención (Generada)'),
        ),
    ]
