# Generated by Django 5.1.6 on 2026-09-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0026_expediente_certificacion_final_escaneada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='solo_mas_de_12_semestres',
            field=models.BooleanField(default=False, help_text='Solo se agregará al expediente de alumnos que cursaron más de 12 semestres.', verbose_name='Exclusivo para más de 12 semestres'),
        ),
    ]
