# Generated by Django 5.1.6 on 2026-03-31 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('expediente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CORRECCION', 'Se requiere corrección'), ('AVANCE', 'Avance del proceso'), ('URGENTE', 'Urgente')], default='INFO', max_length=15, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='¿Leída?')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('url_relacionada', models.CharField(blank=True, max_length=300, verbose_name='URL relacionada (para enlace directo)')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(max_length=20, unique=True, verbose_name='Número de control')),
                ('semestre_egreso', models.CharField(blank=True, max_length=20, verbose_name='Semestre de egreso (ej: Ago-Dic 2024)')),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio general')),
                ('correo_institucional', models.EmailField(blank=True, help_text='Correo @apizaco.tecnm.mx o institucional para notificaciones', max_length=254, verbose_name='Correo institucional')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.carrera', verbose_name='Carrera')),
                ('plan_estudios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expediente.planestudios', verbose_name='Plan de Estudios')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Alumno',
                'verbose_name_plural': 'Perfiles de Alumnos',
            },
        ),
    ]
