# Generated by Django 5.1.6 on 2026-05-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilalumno',
            name='correo_institucional',
        ),
    ]
